# Generated by Django 5.1.3 on 2025-01-01 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_by_alter_event_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 58, 49, 670528, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
